# Generated by Django 4.1.6 on 2023-02-22 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='recepient',
            new_name='recipient',
        ),
    ]
